#!/bin/bash

#==============================================================================
# Gather Binaries Script (Corrected)
#
# This script finds all executable files generated by 'make' inside the 'src'
# subdirectories and copies them into a single 'bin' directory.
#
# It should be run from the root of the 'beebs' project directory after 'make'.
#
#==============================================================================

# The directory where the source code and the compiled binaries are located.
SEARCH_DIR="src"

# The destination directory for the final, collected binaries.
DEST_DIR="bin"

# Exit the script immediately if any command fails.
set -e

# Check if the source directory exists before we do anything.
if [ ! -d "$SEARCH_DIR" ]; then
    echo "Error: Source directory '$SEARCH_DIR' not found."
    echo "Please run this script from the root of the beebs project."
    exit 1
fi

echo "Preparing destination directory: '$DEST_DIR'"
mkdir -p "$DEST_DIR"

echo "Searching for compiled binaries inside '$SEARCH_DIR'..."
echo "--------------------------------------------------"

# Use the 'find' command to locate and copy the files:
#
# "$SEARCH_DIR"             ->  Tell find to look only in the 'src' directory.
# -type f                   ->  Find items that are files.
# -executable               ->  Find files that have execute permissions.
# -exec cp -v -t ... {} +   ->  Execute the copy command for the found files.
#    -v : verbose, prints each file being copied.
#    -t : specifies the target directory.
#    {} + : appends all found files as arguments to a single 'cp' command.

find "$SEARCH_DIR" -type f -executable -exec cp -v -t "$DEST_DIR" {} +

echo "--------------------------------------------------"
echo "Copy complete."
echo "All found binaries have been gathered into the '$DEST_DIR' directory:"
echo
ls -l "$DEST_DIR"